<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="26" started-at="2020-06-10T23:26:37Z" finished-at="2020-06-10T23:26:37Z">
    <groups>
      <group name="regressiontesting">
        <method signature="Dependsongroups.search()[pri:0, instance:Com.TestNG.Dependsongroups@7113b13f]" name="search" class="Com.TestNG.Dependsongroups"/>
      </group> <!-- regressiontesting -->
      <group name="retesting">
        <method signature="Dependsongroups.logout()[pri:0, instance:Com.TestNG.Dependsongroups@7113b13f]" name="logout" class="Com.TestNG.Dependsongroups"/>
      </group> <!-- retesting -->
      <group name="smoketesting">
        <method signature="Dependsongroups.logout()[pri:0, instance:Com.TestNG.Dependsongroups@7113b13f]" name="logout" class="Com.TestNG.Dependsongroups"/>
        <method signature="Dependsongroups.search()[pri:0, instance:Com.TestNG.Dependsongroups@7113b13f]" name="search" class="Com.TestNG.Dependsongroups"/>
      </group> <!-- smoketesting -->
    </groups>
    <test name="Test" duration-ms="26" started-at="2020-06-10T23:26:37Z" finished-at="2020-06-10T23:26:37Z">
      <class name="Com.TestNG.Dependsongroups">
        <test-method status="PASS" signature="logout()[pri:0, instance:Com.TestNG.Dependsongroups@7113b13f]" name="logout" duration-ms="7" started-at="2020-06-10T23:26:37Z" finished-at="2020-06-10T23:26:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="FAIL" signature="search()[pri:0, instance:Com.TestNG.Dependsongroups@7113b13f]" name="search" duration-ms="2" started-at="2020-06-10T23:26:37Z" finished-at="2020-06-10T23:26:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [abc] but found [xyz]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [abc] but found [xyz]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Com.TestNG.Dependsongroups.search(Dependsongroups.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- search -->
      </class> <!-- Com.TestNG.Dependsongroups -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
